import './globals.css'
import { Inter } from 'next/font/google'
import ThemeRegistry from './theme/ThemeRegistry'
import ResponsiveAppBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
      <body className={inter.className}>
        <ResponsiveAppBar/>
        {children}</body>
     </ThemeRegistry>
    </html>
  )
}
